# Generated by Django 4.1.3 on 2023-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoCows', '0003_cows_realborn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borncows',
            name='id_son',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
